### ISSUE TITLE
node-file-logger reverts to default if options.folderPath exists

### ISSUE THREAD

**Issue by bigsurfnl** [routbisu/node-file-logger#1]
In validate options there is a logic error. It initialy creates the logging folder if it does not exist but in subsequent logging actions it reverts to the default. In validateOptions method, first part should be like this:

```
if (options.folderPath) {
    if (!fs.existsSync(options.folderPath)) {
        fs.mkdirSync(options.folderPath);
    }
    defaultOptions.folderPath = options.folderPath;
}
```

**Comment by bigsurfnl** [comment]
Also if the folderPath contains more levels and it does not exist then the mkdirSync will fail. If it has more levels then the folderPath must be created in advance.

**Comment by FireController1847** [comment]
No idea when he'll get around to fixing it. For now, if you want to use the fixed version you can install it via `npm i FireController1847/node-file-logger#patch-1` or `yarn add FireController/node-file-logger#patch-1` and it will use my PR.
